C:\Users\Arafat\Desktop\Final Hand\proximal-Static 1
C:\Users\Arafat\Desktop\Final Hand\strength-Static 1
C:\Users\Arafat\Desktop\Final Hand\strength-Static 1
C:\Users\Arafat\Desktop\Final Hand\strength-Static 1
C:\Users\Arafat\Desktop\Final Hand\strength-Static 1
C:\Users\Arafat\Desktop\Final Hand\Strength-Static 1
C:\Users\Arafat\Desktop\Final Hand\Strength-Static 1
C:\Users\Arafat\Desktop\Final Hand\Strength-Static 1
C:\Users\Arafat\Desktop\Final Hand\Strength-Static 1
C:\Users\Arafat\Desktop\Final Hand\Strength-Static 1
C:\Users\Arafat\Desktop\Final Hand\Strength-Static 1
C:\Users\Arafat\Desktop\Final Hand\Strength-Static 1
C:\Users\Arafat\Desktop\Final Hand\Strength-Static 1
C:\Users\Arafat\Desktop\Final Hand\Strength-Static 1
C:\Users\Arafat\Desktop\Final Hand\Strength-Static 1
C:\Users\Arafat\Desktop\Final Hand\Strength-Static 1
C:\Users\Arafat\Desktop\Final Hand\Strength-hook grip
C:\Users\Arafat\Desktop\Final Hand\Strength-hook grip
C:\Users\Arafat\Desktop\Final Hand\Strength-hook grip
C:\Users\Arafat\Desktop\Final Hand\Strength-hook grip
C:\Users\Arafat\Desktop\Final Hand\Strength-hook grip
C:\Users\Arafat\Desktop\Final Hand\Strength-hook grip
C:\Users\Arafat\Desktop\Final Hand\Servo strength-Static 1
C:\Users\Arafat\Desktop\Final Hand\Servo strength-Static 1
C:\Users\Arafat\Desktop\Final Hand\Servo strength-Static 1
